# Generated by Django 3.2.24 on 2024-02-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='UnderCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categorymodel')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Именная ссылка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('full_price', models.FloatField(verbose_name='Полная цена')),
                ('tradein_price', models.FloatField(verbose_name='Цена в трейд-ин')),
                ('parameter1', models.IntegerField(verbose_name='Ёмкость')),
                ('parameter2', models.IntegerField(verbose_name='Пусковой ток')),
                ('parameter3', models.CharField(max_length=30, verbose_name='Полярность')),
                ('parameter4', models.CharField(max_length=30, verbose_name='Габариты')),
                ('parameter5', models.CharField(max_length=30, verbose_name='Производство')),
                ('parameter6', models.IntegerField(verbose_name='Напряжение')),
                ('parameter7', models.CharField(max_length=30, verbose_name='Гарантия')),
                ('parameter8', models.CharField(max_length=30, verbose_name='Вес')),
                ('inorder', models.BooleanField(default=True, verbose_name='В наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categorymodel')),
                ('under_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.undercategorymodel')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
