# Generated by Django 3.2.24 on 2024-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('car_mark', models.CharField(max_length=40, verbose_name='Марка авто')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='Текст заказчика')),
                ('acum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбрано АКБ')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
